### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by ssteinbach** [SpryFox/DarkConfig#22]
Hi, Thanks for this library!

Is there a callback or function you can implement on objects with the `.applyThis()` function that will be called after a reload/re-apply?  Right now I'm just watching a value in `update`.

**Comment by rdw** [comment]
Yes!  If you implement a PostDoc function, it'll get called after every Reify for the applicable type.  The documentation needs fleshing out, but there's an example in the demo, in PlaneCard.bytes.

**Comment by ssteinbach** [comment]
Perfect!  Thanks @rdw, that sounds like exactly what I was looking for.

I think even annotating the example project a bit could help explain all the features in there - I poked around in that project but hadn't noticed that.

**Comment by rdw** [comment]
Good feedback, thanks!  I'll hopefully make time for that.
