### ISSUE TITLE
C++ Support

### ISSUE THREAD

**Issue by loudedtwist** [SpryFox/DarkConfig#23]
I saw your presentation and it is really impressive, what you have done. Thank you for that =) 
Is it possible to use your library in a C++ project ?

**Comment by rdw** [comment]
Thanks!
DarkConfig relies pretty heavily on the Reflection API, which doesn't exist in C++.  I could imagine using DarkConfig in a C#-only subset of a C++ project, I guess, but it'd require a rewrite to work correctly on pure-C++ objects.
