### ISSUE TITLE
Ability to control logging

### ISSUE THREAD

**Issue by aschearer** [SpryFox/DarkConfig#5]
It would be nice to have the the ability to plug in a custom logger, or at a minimum tweak what logs. Right now DarkConfig spits everything out which makes logs noisy.

**Comment by rdw** [comment]
If the goal is just to reduce noisiness, then `Config.Verbosity = LogVerbosity.Error` should help.

Right now the Platforms are the source of pluggability for log functions, you'd subclass the appropriate Platform object and override Log and LogError.  Maybe needs more docs?  Too cumbersome even if documented?

**Comment by aschearer** [comment]
Awesome, somehow I missed Verbosity. These two things are what I want.
